package gui;
import java.awt.*;
import poo.javabnb.Building;
import poo.javabnb.FontManager;
import style.Style;

public class BuildingWidget extends javax.swing.JPanel {

    public BuildingWidget() {
        initComponents();
    }
    
    public void init(Building b){
        title.setText(b.title);
        host.setText(b.getHost().getName());
        price.setText(String.valueOf(b.price) + "€/noche");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfp = new javax.swing.JButton();
        host = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();

        pfp.setBackground(Style.BG_COLOR);
        pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_default.png"))); // NOI18N
        pfp.setBorder(null);
        pfp.setBorderPainted(false);
        pfp.setContentAreaFilled(false);
        pfp.setDefaultCapable(false);
        pfp.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_default.png"))); // NOI18N
        pfp.setEnabled(false);
        pfp.setFocusPainted(false);
        pfp.setFocusable(false);

        host.setFont(FontManager.boldFont);
        host.setText("Anfitrión");

        title.setFont(FontManager.subtitleFont);
        title.setForeground(Style.TEXT_COLOR);
        title.setText("Title");

        price.setFont(FontManager.boldFont);
        price.setText("Precio por noche");

        rating.setFont(FontManager.boldFont);
        rating.setText("Estrellas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addComponent(host)
                    .addComponent(price)
                    .addComponent(rating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(pfp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(18, 18, 18)
                        .addComponent(host)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs){
        Graphics2D g2 = (Graphics2D) grphcs;
        
        
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel host;
    private javax.swing.JButton pfp;
    private javax.swing.JLabel price;
    private javax.swing.JLabel rating;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}