package gui;

import poo.javabnb.Building;
import poo.javabnb.FontManager;
import style.Style;

public class BuildingWidget extends javax.swing.JPanel {

    public BuildingWidget(Building b) {
        initComponents();
        
        title.setText(b.title);
        address.setText(b.address);
        price.setText(String.valueOf(b.price));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        timeRange = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        address = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_default.png"))); // NOI18N
        add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, -1, -1));

        title.setFont(FontManager.subtitleFont);
        title.setForeground(Style.TEXT_COLOR);
        title.setText("Inmueble");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        rating.setFont(FontManager.regularFont);
        rating.setForeground(Style.TEXT_COLOR);
        rating.setText("5/5");
        add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        timeRange.setFont(FontManager.regularFont);
        timeRange.setForeground(Style.TEXT_COLOR);
        timeRange.setText("Tiempo disponible");
        add(timeRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        price.setFont(FontManager.regularFont);
        price.setForeground(Style.TEXT_COLOR);
        price.setText("10€/noche");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        address.setFont(FontManager.regularFont);
        address.setForeground(Style.TEXT_COLOR);
        address.setText("Dirección");
        add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JButton photo;
    private javax.swing.JLabel price;
    private javax.swing.JLabel rating;
    private javax.swing.JLabel timeRange;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
