package gui;

import javax.swing.JComboBox;
import poo.javabnb.Building;
import poo.javabnb.FontManager;
import style.Style;

public class BuildingPage extends javax.swing.JPanel implements DynamicPage {

    private Building b;
    private boolean saved = false;
    public BuildingPage() {
        initComponents();
        Style.highlightOnHover(submitButton);
        
    }
    
    @Override
    public void reloadContent(){  
      b = App.focusedBuilding;
      saved = App.session.user.pinnedPosts.contains(b.getID());
      name.setText(b.info.title);
      description.setText(b.description);
      host.setText(b.info.host.getName() + (b.info.host.isSuperhost() ? "(Superanfitrión)" : ""));
      rating.setText(String.valueOf(b.info.rating) + " estrellas");
      props.setText(String.valueOf(b.rooms) + " habitaciones · " + String.valueOf(b.baths) + " baños · " + String.valueOf(b.visitors) + " huéspedes");
    }

    @Override
    public void createDynamicContent(){
        
    }
    
    @Override
    public void deleteDynamicContent(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        atrasButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        searchBar = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 0));
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 10));
        jPanel8 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jPanel4 = new javax.swing.JPanel();
        host = new javax.swing.JLabel();
        props = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        description = new javax.swing.JTextArea();
        name = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        saveButton = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jPanel5 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabel2 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(Style.MAIN_COLOR);
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));

        atrasButton.setBackground(Style.MAIN_COLOR);
        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        atrasButton.setBorder(null);
        atrasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        atrasButton.setFocusable(false);
        atrasButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        atrasButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        atrasButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(atrasButton);

        jTextField1.setBackground(Style.INPUT_BG_COLOR);
        jTextField1.setText("Fecha ida");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        searchBar.setBackground(Style.INPUT_BG_COLOR);
        searchBar.setText("Destino");
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        jPanel1.add(searchBar);

        jTextField2.setEditable(false);
        jTextField2.setBackground(Style.INPUT_BG_COLOR);
        jTextField2.setText("Fecha vuelta");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);

        jTextField3.setBackground(Style.INPUT_BG_COLOR);
        jTextField3.setText("nº Personas");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);

        comboBox.setBackground(new java.awt.Color(255, 248, 249));
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Perfil", "Community Guidelines", "Cerrar sesión" }));
        comboBox.setToolTipText("");
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox);

        add(jPanel1);

        jPanel2.setBackground(Style.BG_COLOR);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel6.setBackground(Style.BG_COLOR);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel6.add(filler4);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButton1.setBackground(Style.TRANSPARENT_COLOR);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/example1.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jPanel3.add(jButton1);

        jPanel6.add(jPanel3);
        jPanel6.add(filler1);

        jPanel8.setBackground(Style.TRANSPARENT_COLOR);
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jPanel8.add(filler2);

        jPanel4.setBackground(Style.TRANSPARENT_COLOR);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        host.setBackground(Style.TEXT_COLOR);
        host.setFont(FontManager.boldFont);
        host.setText("Anfitrión: Pedrito (Superanfitrión)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel4.add(host, gridBagConstraints);

        props.setBackground(Style.TEXT_COLOR);
        props.setFont(FontManager.boldFont);
        props.setText("4 huéspedes · 1 baño · 3 habitaciones · 3 camas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel4.add(props, gridBagConstraints);

        rating.setBackground(Style.TEXT_COLOR);
        rating.setFont(FontManager.boldFont);
        rating.setText("5/5 estrellas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel4.add(rating, gridBagConstraints);

        description.setEditable(false);
        description.setBackground(Style.TRANSPARENT_COLOR);
        description.setColumns(20);
        description.setFont(FontManager.regularFont);
        description.setForeground(Style.TEXT_COLOR);
        description.setLineWrap(true);
        description.setRows(5);
        description.setText("Esta es la descripción del inmueble.\n\nEn principio cuando esto sobrepase el tamaño de la preview, habrá un botón de \"Mostrar más\" que mostrará el texto completo.");
        description.setWrapStyleWord(true);
        description.setBorder(null);
        description.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        description.setFocusable(false);
        description.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        jPanel4.add(description, gridBagConstraints);

        name.setBackground(Style.TEXT_COLOR);
        name.setFont(FontManager.titleFont);
        name.setText("Nombre del inmueble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel4.add(name, gridBagConstraints);

        jPanel8.add(jPanel4);

        jPanel9.setBackground(Style.TRANSPARENT_COLOR);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setBackground(Style.TRANSPARENT_COLOR);
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton.setBackground(Style.TRANSPARENT_COLOR);
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveButton.setBorder(null);
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel7.add(saveButton);

        jButton2.setBackground(Style.TRANSPARENT_COLOR);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jButton2);
        jPanel7.add(filler7);

        jPanel9.add(jPanel7);

        jPanel5.setBackground(Style.TRANSPARENT_COLOR);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 8;
        jPanel5.add(jFormattedTextField1, gridBagConstraints);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 8;
        jPanel5.add(jFormattedTextField2, gridBagConstraints);

        jLabel1.setFont(FontManager.boldFont);
        jLabel1.setText("Total XXX€");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        jPanel5.add(jLabel1, gridBagConstraints);

        submitButton.setBackground(Style.MAIN_COLOR);
        submitButton.setFont(FontManager.boldFont);
        submitButton.setForeground(Style.BG_COLOR);
        submitButton.setText("RESERVA");
        submitButton.setBorder(null);
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 12;
        jPanel5.add(submitButton, gridBagConstraints);

        jPanel9.add(jPanel5);

        jPanel8.add(jPanel9);
        jPanel8.add(filler3);

        jPanel6.add(jPanel8);
        jPanel6.add(jLabel2);

        jScrollPane2.setViewportView(jPanel6);

        jPanel2.add(jScrollPane2);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String selectedItem = (String) cb.getSelectedItem();
        System.out.println("Item seleccionado: " + selectedItem);
        switch (selectedItem) {
            case "Perfil":
                App.redirect("PROFILE");
                break;
            case "Post guardados":
                App.redirect("PINNED_POSTS");
                break;
            case "Cerrar sesión":
                App.session.endSession();
                App.redirect("LOGIN");
                break;
            case "Community Guidelines":
                App.redirect("COMMUNITY_GUIDELINES");
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_comboBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saved = !saved;
        if(saved){
            App.session.addPinnedPost(b.getID());
            System.out.println("Añadido el inmueble con id " + String.valueOf(b.getID()) + ". El usuario tiene " + String.valueOf(App.session.user.pinnedPosts.size()) + " posts guardados");
        }
        if(!saved && App.session.user.pinnedPosts.contains(b.getID())){
            App.session.deletePinnedPost(b.getID());
            System.out.println("Eliminado el inmueble con id " + String.valueOf(b.getID()) + ". El usuario tiene " + String.valueOf(App.session.user.pinnedPosts.size()) + " posts guardados");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        App.redirect("MAIN");
    }//GEN-LAST:event_atrasButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasButton;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextArea description;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel host;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel name;
    private javax.swing.JLabel props;
    private javax.swing.JLabel rating;
    private javax.swing.JToggleButton saveButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
