package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import poo.javabnb.Building;
import poo.javabnb.FontManager;
import style.Style;

public class BuildingPage extends javax.swing.JPanel {

    private Building b;
    public BuildingPage() {
        initComponents();
    }
    
    public void reloadInfo(){
      b = App.focusedBuilding;
      name.setText(b.title);
      description.setText(b.description);
      host.setText(b.getHost().getName() + (b.getHost().isSuperhost() ? "(Superanfitrión)" : ""));
      rating.setText(String.valueOf(b.rating) + " estrellas");
      props.setText(String.valueOf(b.rooms) + " habitaciones");
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        host = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        props = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        saveButton = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(Style.MAIN_COLOR);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        searchBar.setBackground(Style.INPUT_BG_COLOR);
        searchBar.setText("Destino");
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        jPanel5.add(searchBar);

        jTextField1.setBackground(Style.INPUT_BG_COLOR);
        jTextField1.setText("Fecha ida");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1);

        jTextField2.setEditable(false);
        jTextField2.setBackground(Style.INPUT_BG_COLOR);
        jTextField2.setText("Fecha vuelta");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2);

        jTextField3.setBackground(Style.INPUT_BG_COLOR);
        jTextField3.setText("nº Personas");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3);

        comboBox.setBackground(new java.awt.Color(255, 248, 249));
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perfil", "Community Guidelines", "Cerrar sesión" }));
        comboBox.setToolTipText("");
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        jPanel5.add(comboBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        jPanel1.add(jPanel5, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(Style.BG_COLOR);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        host.setBackground(Style.TEXT_COLOR);
        host.setFont(FontManager.regularFont);
        host.setText("Anfitrión: Pedrito (Superanfitrión)");
        jPanel2.add(host, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 520, 20));

        name.setBackground(Style.TEXT_COLOR);
        name.setFont(FontManager.titleFont);
        name.setText("Nombre del inmueble");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 520, 50));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        description.setEditable(false);
        description.setColumns(20);
        description.setFont(FontManager.regularFont);
        description.setForeground(Style.TEXT_COLOR);
        description.setLineWrap(true);
        description.setRows(5);
        description.setText("Esta es la descripción del inmueble.\n\nEn principio cuando esto sobrepase el tamaño de la preview, habrá un botón de \"Mostrar más\" que mostrará el texto completo.");
        description.setWrapStyleWord(true);
        description.setBorder(null);
        description.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        description.setFocusable(false);
        description.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(description);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        props.setBackground(Style.TEXT_COLOR);
        props.setFont(FontManager.regularFont);
        props.setText("4 huéspedes · 1 baño · 3 habitaciones · 3 camas");
        jPanel2.add(props, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 520, 20));

        rating.setBackground(Style.TEXT_COLOR);
        rating.setFont(FontManager.regularFont);
        rating.setText("5/5 estrellas");
        jPanel2.add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 520, 20));

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel2.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String selectedItem = (String) cb.getSelectedItem();
        System.out.println("Item seleccionado: " + selectedItem);
        switch (selectedItem) {
            case "Perfil":
                App.redirect("PROFILE");
                break;
            case "Post guardados":
                App.redirect("PINNED_POSTS");
                break;
            case "Cerrar sesión":
                App.session.endSession();
                App.redirect("LOGIN");
                break;
            case "Community Guidelines":
                App.redirect("COMMUNITY_GUIDELINES");
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_comboBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel host;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel name;
    private javax.swing.JLabel props;
    private javax.swing.JLabel rating;
    private javax.swing.JToggleButton saveButton;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
