/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import poo.javabnb.FontManager;

/**
 *
 * @author Alumno
 */
public class EULAPage extends javax.swing.JPanel {

    /**
     * Creates new form EULAPage
     */
    public EULAPage() {
        initComponents();
        titleEula.setBorder(null);
        eulaScroll.setBorder(null);
        FontManager.useFont(titleEula, FontManager.titleFont, Color.BLACK);
        FontManager.useFont(leidoButton, FontManager.boldFont, Color.black);
        FontManager.useFont(eulaText, FontManager.regularFont, Color.BLACK);
        leidoButton.setBorder(null);


        leidoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                App.redirect("REGISTER");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleEula = new javax.swing.JLabel();
        eulaScroll = new javax.swing.JScrollPane();
        eulaText = new javax.swing.JLabel();
        leidoButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        titleEula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEula.setText("EULA");
        add(titleEula, java.awt.BorderLayout.PAGE_START);

        eulaText.setText("To be implemented");
        eulaText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        eulaScroll.setViewportView(eulaText);

        add(eulaScroll, java.awt.BorderLayout.CENTER);

        leidoButton.setText("Hecho");
        leidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leidoButtonActionPerformed(evt);
            }
        });
        add(leidoButton, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void leidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leidoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leidoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane eulaScroll;
    private javax.swing.JLabel eulaText;
    private javax.swing.JButton leidoButton;
    private javax.swing.JLabel titleEula;
    // End of variables declaration//GEN-END:variables
}
