package gui;
import java.awt.Dimension;
import java.io.File;
import polaris.Polaris;
import poo.javabnb.util.FontManager;
import poo.javabnb.util.Images;


public class NewBuildingPage extends javax.swing.JFrame {

    File image;
    public NewBuildingPage() {
        initComponents();
        Polaris.highlightOnHover(jButton2);
        this.setMinimumSize(new Dimension(500, 700));
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        titleInput = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionInput = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        addressInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        roomsInput = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        bathsInput = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        visitorsInput = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hashtagsInput = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        imageChooser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        imageFileLocationLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo inmueble");
        setBackground(Polaris.BG_COLOR);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(Polaris.BG_COLOR);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(FontManager.titleFont);
        jLabel2.setForeground(Polaris.TEXT_COLOR);
        jLabel2.setText("Nuevo inmueble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(FontManager.regularFont);
        jLabel3.setForeground(Polaris.TEXT_COLOR);
        jLabel3.setText("Título");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        priceInput.setBackground(Polaris.INPUT_BG_COLOR);
        priceInput.setFont(FontManager.regularFont);
        priceInput.setForeground(Polaris.TEXT_COLOR);
        priceInput.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(priceInput, gridBagConstraints);

        jLabel4.setFont(FontManager.regularFont);
        jLabel4.setForeground(Polaris.TEXT_COLOR);
        jLabel4.setText("Precio por noche");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        titleInput.setBackground(Polaris.INPUT_BG_COLOR);
        titleInput.setBorder(null);
        titleInput.setForeground(Polaris.TEXT_COLOR);
        titleInput.setFont(FontManager.regularFont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(titleInput, gridBagConstraints);

        jLabel5.setFont(FontManager.regularFont);
        jLabel5.setForeground(Polaris.TEXT_COLOR);
        jLabel5.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        descriptionInput.setBackground(Polaris.INPUT_BG_COLOR);
        descriptionInput.setColumns(20);
        descriptionInput.setFont(FontManager.regularFont);
        descriptionInput.setForeground(Polaris.TEXT_COLOR);
        descriptionInput.setLineWrap(true);
        descriptionInput.setRows(5);
        descriptionInput.setWrapStyleWord(true);
        descriptionInput.setBorder(null);
        jScrollPane1.setViewportView(descriptionInput);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel6.setFont(FontManager.regularFont);
        jLabel6.setForeground(Polaris.TEXT_COLOR);
        jLabel6.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        addressInput.setBackground(Polaris.INPUT_BG_COLOR);
        addressInput.setFont(FontManager.regularFont);
        addressInput.setForeground(Polaris.TEXT_COLOR);
        addressInput.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(addressInput, gridBagConstraints);

        jLabel7.setFont(FontManager.regularFont);
        jLabel7.setForeground(Polaris.TEXT_COLOR);
        jLabel7.setText("Tipo de inmueble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        typeComboBox.setBackground(Polaris.INPUT_BG_COLOR);
        typeComboBox.setFont(FontManager.regularFont);
        typeComboBox.setForeground(Polaris.TEXT_COLOR);
        typeComboBox.setMaximumRowCount(3);
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento" }));
        typeComboBox.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(typeComboBox, gridBagConstraints);

        jLabel8.setFont(FontManager.regularFont);
        jLabel8.setForeground(Polaris.TEXT_COLOR);
        jLabel8.setText("Habitaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        roomsInput.setBackground(Polaris.INPUT_BG_COLOR);
        roomsInput.setBorder(null);
        roomsInput.setForeground(Polaris.TEXT_COLOR);
        roomsInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        roomsInput.setFont(FontManager.regularFont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(roomsInput, gridBagConstraints);

        jLabel9.setFont(FontManager.regularFont);
        jLabel9.setForeground(Polaris.TEXT_COLOR);
        jLabel9.setText("Baños");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        bathsInput.setBackground(Polaris.INPUT_BG_COLOR);
        bathsInput.setBorder(null);
        bathsInput.setForeground(Polaris.TEXT_COLOR);
        bathsInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        bathsInput.setFont(FontManager.regularFont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(bathsInput, gridBagConstraints);

        jLabel10.setFont(FontManager.regularFont);
        jLabel10.setForeground(Polaris.TEXT_COLOR);
        jLabel10.setText("Nº máx. residentes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        visitorsInput.setBackground(Polaris.INPUT_BG_COLOR);
        visitorsInput.setBorder(null);
        visitorsInput.setForeground(Polaris.TEXT_COLOR);
        visitorsInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        visitorsInput.setFont(FontManager.regularFont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(visitorsInput, gridBagConstraints);

        jLabel11.setFont(FontManager.regularFont);
        jLabel11.setForeground(Polaris.TEXT_COLOR);
        jLabel11.setText("Etiquetas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        hashtagsInput.setBackground(Polaris.INPUT_BG_COLOR);
        hashtagsInput.setColumns(20);
        hashtagsInput.setFont(FontManager.regularFont);
        hashtagsInput.setForeground(Polaris.TEXT_COLOR);
        hashtagsInput.setRows(5);
        hashtagsInput.setBorder(null);
        jScrollPane2.setViewportView(hashtagsInput);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jLabel12.setFont(FontManager.regularFont);
        jLabel12.setForeground(Polaris.TEXT_COLOR);
        jLabel12.setText("Imagen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(jLabel12, gridBagConstraints);

        imageChooser.setFont(FontManager.boldFont);
        imageChooser.setText("Elegir imagen");
        imageChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageChooserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(imageChooser, gridBagConstraints);

        jButton2.setBackground(Polaris.MAIN_COLOR);
        jButton2.setFont(FontManager.boldFont);
        jButton2.setForeground(Polaris.BG_COLOR);
        jButton2.setText("Enviar");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jButton2, gridBagConstraints);

        jLabel13.setFont(FontManager.boldFont);
        jLabel13.setForeground(Polaris.TEXT_COLOR);
        jLabel13.setText("Datos generales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 5, 0);
        jPanel1.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(FontManager.boldFont);
        jLabel14.setForeground(Polaris.TEXT_COLOR);
        jLabel14.setText("Propiedades del inmueble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 5, 0);
        jPanel1.add(jLabel14, gridBagConstraints);

        imageFileLocationLabel.setText("root");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        jPanel1.add(imageFileLocationLabel, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void imageChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageChooserActionPerformed
        image = Images.createImageChooser();
        // In case the action is cancelled
        if(image != null){
           imageFileLocationLabel.setText(image.getAbsolutePath()); 
        }
        
    }//GEN-LAST:event_imageChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBuildingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JFormattedTextField bathsInput;
    private javax.swing.JTextArea descriptionInput;
    private javax.swing.JTextArea hashtagsInput;
    private javax.swing.JButton imageChooser;
    private javax.swing.JLabel imageFileLocationLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceInput;
    private javax.swing.JFormattedTextField roomsInput;
    private javax.swing.JFormattedTextField titleInput;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JFormattedTextField visitorsInput;
    // End of variables declaration//GEN-END:variables
}
