package gui;
import polaris.DynamicPage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import polaris.Polaris;
import poo.javabnb.Building;
import poo.javabnb.Client;
import poo.javabnb.Host;
import poo.javabnb.util.FontManager;
import poo.javabnb.util.Hashing;
import poo.javabnb.util.Images;

public class ProfilePage extends javax.swing.JPanel implements DynamicPage {
    
    private boolean isEditing = false;
    
    public ArrayList<BuildingWidget> widgets;
    
    public ProfilePage() {
        initComponents();
        widgets = new ArrayList<>();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        backButton.addActionListener((ActionEvent e) -> {
            App.redirect("MAIN");
        });
        
        editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                isEditing = true;
                userPhoneLabel.setEditable(isEditing);
                userMailLabel.setEditable(isEditing);
                nameLabel.setEditable(isEditing);
            }
        }); 
    }
    
    @Override
    public void reloadContent(){
        deleteDynamicContent();
        newPostButton.setVisible(App.session.isHost);
        pinnedPostsLabel.setText(App.session.isHost? "Mis inmuebles" : "Inmuebles guardados");
        userNameLabel.setText(App.session == null? "null" : App.session.user.getName());
        nameLabel.setText(App.session == null? "null" : App.session.user.getName());
        userMailLabel.setText(App.session == null? "null" : App.session.user.getMail());
        userPhoneLabel.setText(App.session == null? "null" : App.session.user.getNumber());
        
        try{
            ImageIcon pfpIcon = new ImageIcon(getClass().getResource("/images/" + App.session.user.getDNI() + "1.png"));
            pfpIcon.getImage().flush();
            pfp.setIcon(pfpIcon);
        }
        catch(Exception e){
           pfp.setIcon(new ImageIcon(getClass().getResource("/images/profile_default.png")));
        }
        
        try{           
            ImageIcon bannerIcon = new ImageIcon(getClass().getResource("/images/" + App.session.user.getDNI() + "3.png"));
            bannerIcon.getImage().flush();
            banner.setIcon(bannerIcon);
        }
        catch(Exception e){
           banner.setIcon(new ImageIcon(getClass().getResource("/images/banner.png")));
        }

        
        App.session.updateSession();
        createDynamicContent();
    }
    
    @Override
    public void deleteDynamicContent(){
        for(BuildingWidget bw : widgets){
            content.remove(bw);
        }
    }
    
    @Override
    public void createDynamicContent(){
        ArrayList<Building> array = App.session.isHost ? ((Host) App.session.user).getAllBuildings() : App.buildings.entries;
        
        int max = App.session.isHost? array.size() : App.session.user.pinnedPosts.size();

        int i = 0;
        int rows = 0;
        
        while(i < max){
            for(int x = 0; x < App.frame.getWidth() && i < max; x += 330){
                BuildingWidget bw = new BuildingWidget();
                widgets.add(bw);
                content.add(bw, new AbsoluteConstraints(160 + x, 520 + 330*rows, -1, -1));
                bw.init(
                    App.session.isHost ? array.get(i): App.buildings.entries.get(App.session.user.pinnedPosts.get(i) - 1) 
                );
                ++i;
            }
            ++rows;
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        pfp = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        banner = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        mailLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        mailLabel = new javax.swing.JLabel();
        userMailLabel = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        phoneLabel = new javax.swing.JLabel();
        userPhoneLabel = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 0));
        jPanel1 = new javax.swing.JPanel();
        pinnedPostsLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        newPostButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(polaris.Polaris.BG_COLOR);
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(polaris.Polaris.TRANSPARENT_COLOR);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backButton.setFocusable(false);
        content.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.setBackground(Polaris.TRANSPARENT_COLOR);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameLabel.setFont(FontManager.titleFont);
        userNameLabel.setText("Nombre");
        jPanel2.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        pfp.setBackground(polaris.Polaris.BG_COLOR);
        pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_default.png"))); // NOI18N
        pfp.setBorder(null);
        pfp.setBorderPainted(false);
        pfp.setContentAreaFilled(false);
        pfp.setDefaultCapable(false);
        pfp.setFocusPainted(false);
        pfp.setFocusable(false);
        pfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfpActionPerformed(evt);
            }
        });
        jPanel2.add(pfp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        editButton.setText("Editar perfil");
        editButton.setBorder(null);
        editButton.setBorderPainted(false);
        jPanel2.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        content.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 330, 180));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner.png"))); // NOI18N
        banner.setBorder(null);
        banner.setBorderPainted(false);
        banner.setDisabledIcon(null);
        banner.setFocusPainted(false);
        banner.setFocusable(false);
        banner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        banner.setRequestFocusEnabled(false);
        banner.setRolloverEnabled(false);
        banner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannerActionPerformed(evt);
            }
        });
        content.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setLayout(new java.awt.GridLayout());

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        mailLabel1.setFont(FontManager.boldFont);
        mailLabel1.setText("Nombre");
        jPanel8.add(mailLabel1);

        nameLabel.setEditable(false);
        nameLabel.setText("****");
        jPanel8.add(nameLabel);

        jPanel3.add(jPanel8);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        mailLabel.setFont(FontManager.boldFont);
        mailLabel.setText("Correo");
        jPanel5.add(mailLabel);

        userMailLabel.setEditable(false);
        userMailLabel.setText("****");
        jPanel5.add(userMailLabel);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        phoneLabel.setFont(FontManager.boldFont);
        phoneLabel.setText("Teléfono");
        jPanel6.add(phoneLabel);

        userPhoneLabel.setEditable(false);
        userPhoneLabel.setText("****");
        jPanel6.add(userPhoneLabel);

        jPanel3.add(jPanel6);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jButton2.setText("Guardar cambios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 12;
        jPanel9.add(jButton2, gridBagConstraints);

        jPanel3.add(jPanel9);

        jPanel4.add(jPanel3);
        jPanel4.add(filler1);

        jPanel1.setLayout(new java.awt.GridLayout());

        pinnedPostsLabel.setFont(FontManager.titleFont);
        pinnedPostsLabel.setForeground(polaris.Polaris.TEXT_COLOR);
        pinnedPostsLabel.setText("Inmuebles guardados");
        jPanel1.add(pinnedPostsLabel);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        newPostButton.setBackground(Polaris.MAIN_COLOR);
        newPostButton.setFont(FontManager.boldFont);
        newPostButton.setForeground(Polaris.BG_COLOR);
        newPostButton.setText("Crear inmueble...");
        newPostButton.setBorder(null);
        newPostButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPostButtonActionPerformed(evt);
            }
        });
        jPanel7.add(newPostButton);

        jPanel1.add(jPanel7);

        jPanel4.add(jPanel1);

        content.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 840, 140));

        jScrollPane1.setViewportView(content);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void pfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfpActionPerformed
        File file = Images.createImageChooser();
        Images.resizeImage(file, "./src/main/resources/images/" + App.session.user.getDNI() + "1.png", 150, 150);
        Images.resizeImage(file, "./src/main/resources/images/" + App.session.user.getDNI() + "2.png", 80, 80);
        App.redirect("PROFILE");
    }//GEN-LAST:event_pfpActionPerformed

    private void bannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannerActionPerformed
        File file = Images.createImageChooser();
        Images.resizeImage(file, "./src/main/resources/images/" + App.session.user.getDNI() + "3.png", 1920, 250);
        App.redirect("PROFILE");
    }//GEN-LAST:event_bannerActionPerformed

    private void newPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPostButtonActionPerformed
        new NewBuildingPage().main(null);
    }//GEN-LAST:event_newPostButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        App.session.user.setInfo(nameLabel.getText(), userMailLabel.getText(), userPhoneLabel.getText(), Hashing.hashPassword(App.session.user.getPassword()));
        App.session.updateSession();
        isEditing = false;
        userPhoneLabel.setEditable(isEditing);
        userMailLabel.setEditable(isEditing);
        nameLabel.setEditable(isEditing);
        App.redirect("PROFILE");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton banner;
    private javax.swing.JPanel content;
    private javax.swing.JButton editButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JLabel mailLabel1;
    private javax.swing.JTextField nameLabel;
    private javax.swing.JButton newPostButton;
    private javax.swing.JButton pfp;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel pinnedPostsLabel;
    private javax.swing.JTextField userMailLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userPhoneLabel;
    // End of variables declaration//GEN-END:variables

}
