package gui;
import polaris.DynamicPage;
import poo.javabnb.Client;
import poo.javabnb.util.FontManager;
import poo.javabnb.Building;
import poo.javabnb.Reservation;
import polaris.*;

public class ReservationWidget extends javax.swing.JPanel {
    private Building building;
    private Reservation reservation;

    public ReservationWidget() {
        initComponents();
    }
    public void init(Building b, Reservation r){
        this.building = b;
        this.reservation = r;
        Userlabel.setText(r.getClient().getName());
        BuildingLabel.setText(b.info.title);
        dateBoundsLabel.setText(r.toString());
        cancelReservation.setVisible(
                App.isAdmin || 
                App.session.getUser().getDNI().equals(r.getClient().getDNI()) || 
                App.session.getUser().getDNI().equals(b.info.host.getDNI()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Userlabel = new javax.swing.JLabel();
        cancelReservation = new javax.swing.JButton();
        dateBoundsLabel = new javax.swing.JLabel();
        BuildingLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Userlabel.setFont(FontManager.boldFont);
        Userlabel.setText("Nombre Usuario");
        Userlabel.setToolTipText("");
        add(Userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 40));

        cancelReservation.setBackground(Polaris.TRANSPARENT_COLOR);
        cancelReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelReservation.png"))); // NOI18N
        cancelReservation.setBorder(null);
        cancelReservation.setBorderPainted(false);
        cancelReservation.setContentAreaFilled(false);
        cancelReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelReservation.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelReservation.png"))); // NOI18N
        cancelReservation.setEnabled(false);
        cancelReservation.setFocusable(false);
        cancelReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelReservationMouseClicked(evt);
            }
        });
        cancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationActionPerformed(evt);
            }
        });
        add(cancelReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, 80));

        dateBoundsLabel.setFont(FontManager.boldFont);
        dateBoundsLabel.setText("Bounds");
        dateBoundsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(dateBoundsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 40));

        BuildingLabel.setFont(FontManager.boldFont);
        BuildingLabel.setText("Inmueble");
        BuildingLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(BuildingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelReservationMouseClicked
       int index = building.getReservationIndex(reservation);
       if (index != -1) {
        building.getReservations().remove(index);
        App.buildings.saveData("./src/main/resources/data/b_data.dat");
        ((DynamicPage) App.currentPanel).reload();
        }
    }//GEN-LAST:event_cancelReservationMouseClicked

    private void cancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelReservationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuildingLabel;
    private javax.swing.JLabel Userlabel;
    private javax.swing.JButton cancelReservation;
    private javax.swing.JLabel dateBoundsLabel;
    // End of variables declaration//GEN-END:variables
}
