/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import polaris.DynamicPage;
import poo.javabnb.Client;
import poo.javabnb.util.FontManager;
import poo.javabnb.Building;
import poo.javabnb.Reservation;

/**
 *
 * @author guille
 */
public class ReservationWidget extends javax.swing.JPanel {
    private Building building;
    private Reservation reservation;
    /**
     * Creates new form ReservationWidget
     */
    public ReservationWidget() {
        initComponents();
    }
    public void init(Client c, Building b, Reservation r){
        this.building = b;
        this.reservation = r;
        Userlabel.setText(c.getName());
        dateBoundsLabel.setText(r.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Userlabel = new javax.swing.JLabel();
        warning = new javax.swing.JButton();
        dateBoundsLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Userlabel.setFont(FontManager.boldFont);
        Userlabel.setText("Nombre Usuario");
        add(Userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 40));

        warning.setBackground(Polaris.TRANSPARENT_COLOR);
        warning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelReservation.png"))); // NOI18N
        warning.setBorder(null);
        warning.setBorderPainted(false);
        warning.setContentAreaFilled(false);
        warning.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        warning.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelReservation.png"))); // NOI18N
        warning.setEnabled(false);
        warning.setFocusable(false);
        warning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningActionPerformed(evt);
            }
        });
        add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, 60));

        dateBoundsLabel.setFont(FontManager.boldFont);
        dateBoundsLabel.setText("Bounds");
        add(dateBoundsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void warningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningActionPerformed
       int index = building.getReservationIndex(reservation);
       if (index != -1) {
        building.getReservations().remove(index);
        App.buildings.saveData("./src/main/resources/data/b_data.dat");
        ((DynamicPage) App.currentPanel).reload();
        }
    }//GEN-LAST:event_warningActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Userlabel;
    private javax.swing.JLabel dateBoundsLabel;
    private javax.swing.JButton warning;
    // End of variables declaration//GEN-END:variables
}
