package gui;

import javax.swing.ImageIcon;
import polaris.*;
import poo.javabnb.Client;
import poo.javabnb.Particular;
import poo.javabnb.util.FontManager;
import poo.javabnb.util.Images;


public class UserWidget extends javax.swing.JPanel {

    int index;
    Client client;
    public UserWidget() {
        initComponents();
        
    }
    
    public void init(Client c, int index){
        
        name.setText(c.getName());
        mail.setText(c.getMail());
        try{
            pfp.setDisabledIcon(new ImageIcon(getClass().getResource("/images/" + c.getDNI() + "1.png")));
        }
        catch(Exception e){
            pfp.setDisabledIcon(new ImageIcon(getClass().getResource("/images/profile_default.png")));
        }
        this.index = index;
        this.client = c;
        
        vip.setVisible(false);
        if(App.isAdmin && client instanceof Particular){
            vip.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundedPanel(20);
        pfp = new javax.swing.JButton();
        mail = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        vip = new javax.swing.JButton();
        ban = new javax.swing.JButton();
        jPanel2 = new RoundedPanel(20);

        setBackground(Polaris.TRANSPARENT_COLOR);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(Polaris.BG_HIGHLIGHT_COLOR);
        jPanel1.setOpaque(false);

        pfp.setBackground(polaris.Polaris.BG_COLOR);
        pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_default.png"))); // NOI18N
        pfp.setBorder(null);
        pfp.setBorderPainted(false);
        pfp.setContentAreaFilled(false);
        pfp.setDefaultCapable(false);
        pfp.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile_default.png"))); // NOI18N
        pfp.setEnabled(false);
        pfp.setFocusPainted(false);
        pfp.setFocusable(false);

        mail.setFont(FontManager.regularFont);
        mail.setForeground(polaris.Polaris.TEXT_COLOR);
        mail.setText("mail");

        name.setFont(FontManager.titleFont);
        name.setForeground(polaris.Polaris.TEXT_COLOR);
        name.setText("Nombre");

        vip.setBackground(Polaris.TRANSPARENT_COLOR);
        vip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        vip.setBorder(null);
        vip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipActionPerformed(evt);
            }
        });

        ban.setBackground(Polaris.TRANSPARENT_COLOR);
        ban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove_pople.png"))); // NOI18N
        ban.setBorder(null);
        ban.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pfp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vip)
                    .addComponent(ban))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ban)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vip)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 370, 170));

        jPanel2.setBackground(Polaris.SHADOW_COLOR);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipActionPerformed
        if ((client instanceof Particular && !((Particular)client).isVIP())){
            vip.setIcon(Images.getIcon("/images/star_filled.png"));
            ((Particular)client).setVIP(true);
        }
        else{
             vip.setIcon(Images.getIcon("/images/star.png"));
             ((Particular)client).setVIP(false);
             }
        
    }//GEN-LAST:event_vipActionPerformed

    private void banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banActionPerformed
        App.db.remove(index);
        App.db.saveData("./src/main/resources/data/data.dat");
        ((DynamicPage) App.currentPanel).reload();
    }//GEN-LAST:event_banActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ban;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel name;
    private javax.swing.JButton pfp;
    private javax.swing.JButton vip;
    // End of variables declaration//GEN-END:variables
}
